feat: 스터디 폭파기능 구현 완료 (#148)
lv4-project/Woowahan-Tech-Co-learning pull request #149
Opened 2019-12-20 08:27 UTC by ddu0422

BadRequestExeption은 오늘 정한 내용인데 나중에 공유해드리겠습니다.

2019-12-20 18:45 UTC, ep1stas1s requested changes
크... Advice부터 공용 exception, mock test까지...
전반적으로 깔끔하게 잘 구현하셨네요:100:
혼동되는 부분이 있어서 몇 가지 코멘트 남겼습니다

2019-12-20 18:45 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/common/CommonRestControllerAdvice.java
> +public class CommonRestControllerAdvice {
:+1:

2019-12-20 18:45 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
> +    }
헷갈려서 그러는데...
해당 method가 특정 study의 참가자를 조회하는건가요?
만약 맞다면 `/{studyId}/participants`와 같으 pathvariable을 받아야 할 것 같아요

2019-12-20 18:45 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/domain/exception/NotPresenterException.java
> +public class NotPresenterException extends BadRequestException {
:+1:

2019-12-20 18:45 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
> +        return studyParticipantRepository.findAll().size();
Repository에  `countByStudy(Study study)` 혹은 `count()`를 사용해보는 것도 좋을 것 같아요

2019-12-20 18:45 UTC, ep1stas1s commented on src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
> +                .jsonPath("$").isEqualTo(2);
취향이긴 하지만 다른 분들이 객체를 리턴받아서 테스트를 진행했어요...

2019-12-20 18:45 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
> +        User user = userService.findById(userInfoDto.getId());
`userInfoDto`의 id로 DB조회하지 않고, 바로 study에 넘겨주는 것은 어떤가요?
이미 로그인한 유저의 id이기 때문에 따로 조회할 필요가 없다고 생각합니다.

2019-12-21 03:43 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
> +    }
사실 테스트용으로 만들었는데 나중에도 필요할 것 같네요 ㅎㅎ

2019-12-21 03:44 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
> +        return studyParticipantRepository.findAll().size();
그런게 있었군요 ㅎㅎ 기억이 안났습니당

2019-12-21 03:49 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
> +        User user = userService.findById(userInfoDto.getId());
아이디로만 확인한다 !! 라는거죠? 굳굳

2019-12-21 03:50 UTC, ddu0422 commented on src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
> +                .jsonPath("$").isEqualTo(2);
사이즈만 가져오는 로직은 없더라구요 이 부분은 좀 더 고민해볼게요

2019-12-21 03:51 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
> +    }
앗 테스트용이면 신경 안쓰셔도 됩니다ㅎㅎ

2019-12-21 03:54 UTC, ep1stas1s commented on src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
> +                .jsonPath("$").isEqualTo(2);
```java
.expectBody(Integer.class)
.returnResult()
.getResponseBody();
```
으로 쭉쭉 써내려가면 가능은한데,
음... 저도 사실 뭐가 더 괜찮은지 모르겠어서 애매하게 남겼었숩니다...

2019-12-21 06:28 UTC, ep1stas1s approved these changes
주말에도 사장님의 압박때문에 우리두호가ㅠㅠ
고생하셨습니다!

2019-12-21 06:28 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyParticipant.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
Default가 PUBLIC 일거에용

2019-12-21 06:31 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyParticipant.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
통일하려고 명시했습니당

2019-12-21 06:42 UTC, merged