feat: 회원 CRUD 기능 (#12)
lv4-project/Woowahan-Tech-Co-learning pull request #33
Opened 2019-12-02 09:23 UTC by green4469

2019-12-02 15:56 UTC, ep1stas1s requested changes
첫 주차부터 고생하셨습니다!🦄🦛
짧은 시간안에 vue부터 back까지...
승차감 좋은 게 벌써 느껴지네요~😎

악플다는 게 생각보다 재밌네요^^

2019-12-02 15:56 UTC, ep1stas1s commented on src/frontend/src/components/user/SignUpForm.vue
> +        <v-btn @click="requestSignUp" block tile color="grey" dark>회원 가입</v-btn>
한 줄에 속성 하나!

2019-12-02 15:56 UTC, ep1stas1s commented on src/frontend/src/components/user/SignUpForm.vue
> +        const request = require('request');
이 부분은 정확히 모르는데, 공통으로 사용하는 건 뺄 수 있는 방법을 찾아보는 게 좋을 것 같아요
사장님에게 여쭤보거나ㅎㅎ

2019-12-02 15:56 UTC, ep1stas1s commented on src/frontend/src/components/user/UserProfile.vue
> +        window.console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
log는 test용인가용?

2019-12-02 15:56 UTC, ep1stas1s commented on src/frontend/src/components/user/SignUpForm.vue
> +        :append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
삼항연산자... 그는 과연 javascript인가? HTML인가? (backtick vs single quote)

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +    public ResponseEntity<UserInfoDto> read(@PathVariable long userId) {
```suggestion
    public ResponseEntity<UserInfoDto> read(@PathVariable Long userId) {
```
Entity의 경우 wrapper type을 사용하는데 이 부분은 어떡하는 것이 좋을까요?

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +        userService.update(userUpdateDto, 1);
`1`은 test용인가용?

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
> +        this.nickName = updateUser.getNickName();
```suggestion
        this.nickName = updateUser.nickName;
```

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public long save(UserCreateDto userCreateDto) {
Wrapper type?

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public User findById(long userId) {
다른 곳에서 사용할까봐 public으로 남겨두신건가요?

2019-12-02 15:56 UTC, ep1stas1s commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public UserInfoDto findInfoDtoById(long userId) {
흠...

2019-12-02 15:56 UTC, ep1stas1s commented on src/test/java/woowahan/anifarm/tecolearning/user/controller/UserControllerTest.java
> +                .isOk();
```
webTestClient.post()
                .uri("/api/users/signup")
                .body(Mono.just(new UserCreateDto("green4469@woowahan.com", "moomindev", "")), UserCreateDto.class)
                .exchange()
                .expectStatus()
                .isOk();
```
Body로 UserCreateDto 객체를 보내는 건 어떨까요?

2019-12-02 15:58 UTC, ep1stas1s commented on src/frontend/src/components/user/SignUpForm.vue
> +        counter
잘 못 이해하는 것일 수도 있지만,
counter같은 경우는 닉네임에 `:counter="10"`같이 쓰는 것도 좋을 것 같아요!

2019-12-02 23:45 UTC, Deocksoo commented on src/frontend/src/components/user/SignUpForm.vue
> +        :append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
저는 backtick에 한표!

2019-12-03 00:42 UTC, ddu0422 reviewed
고생하셨어요~ 
간단한 피드백 남겼습니다

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +    private UserService userService;
final 키워드를 사용하여 불변을 유지하는건 어떨까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
> +    @Column(nullable = false)
length를 지정하는건 어떨까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/exception/UserCreateException.java
> +        super("사용자 생성 실패", cause);
상수로 빼는건 어떨까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/exception/UserNotFoundException.java
> +    public static final String ERROR_MSG = "사용자를 찾지 못했습니다.";
convention !!
해당 예외를 테스트하는 코드를 추가하는건 어떤가요?
Exception 안에 있는 상수이니 상수명은 MESSAGE는 어떤가요?

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +        return ResponseEntity.ok().build();
convention !!

2019-12-03 00:42 UTC, ddu0422 commented on src/frontend/src/components/user/SignUpForm.vue
> +  export default {
`use strict`를 작성해주세요 !

2019-12-03 00:42 UTC, ddu0422 commented on src/frontend/src/components/user/UserProfile.vue
> +      let temp = this;
temp가 변수 타입으로 const를 가져도 property의 값은 바꿀 수 있지 않나요?

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
> +    @Id
convention !!

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    private UserRepository userRepository;
여기도 final 키워드를 명시하여 불변을 유지해보아요~

2019-12-03 00:42 UTC, ddu0422 commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +            throw new UserCreateException(error);
log를 추가하는 건 어떨까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/test/java/woowahan/anifarm/tecolearning/user/service/UserServiceTest.java
> +    private UserService userService;
convention을 참고해볼까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/test/java/woowahan/anifarm/tecolearning/user/controller/UserControllerTest.java
> +                .uri("/api/users/signup")
/api/users/ 가 공통이네요
Controller에서 중복을 제거 한 것처럼 여기도 중복을 제거하는건 어떨까요?

2019-12-03 00:42 UTC, ddu0422 commented on src/frontend/src/components/user/SignUpForm.vue
> +        @click:append="showPassword = !showPassword"
@click은 vue 속성이 아닐까요?

2019-12-03 04:58 UTC, yunheehyeon commented on src/frontend/src/components/user/UserProfile.vue
> +        window.console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
네 지금은 지우겠습니다.

2019-12-03 05:18 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +    public ResponseEntity<UserInfoDto> read(@PathVariable long userId) {
Entity만 wrapper 사용 나머지는 기본 타입으로 사용합시다!

2019-12-03 05:19 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +        userService.update(userUpdateDto, 1);
네 아직 로그인이 구현되지 않아서...ㅎ

2019-12-03 05:28 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
> +        this.nickName = updateUser.getNickName();
왜 바꿔야한다고 생각하시나요? 고래의 생각을 알려주세요

2019-12-03 05:29 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public long save(UserCreateDto userCreateDto) {
위와 동일합니다.

2019-12-03 05:30 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public User findById(long userId) {
지금은 아니지만 다른 서비스에서 사용할 수 있을거 같아서 public으로 했습니다.

2019-12-03 05:32 UTC, green4469 commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public User findById(long userId) {
StudyService 에서 persist 된 User (즉, id 를 갖는 유저) 가 필요할 수 있을거라 생각했습니다. (예를 들면 Study 에 List<User> 로 스터디원을 가지고 있고 여기에 새 유저를 id 로 추가하고 싶은 상황)

2019-12-03 05:33 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +    public UserInfoDto findInfoDtoById(long userId) {
흠... user는 중복되어서 지웠습니다.  dto로 변환 할 때 assembler 클래스를 사용할 지 생각해봐야 할거 같습니다.

2019-12-03 05:33 UTC, green4469 commented on src/test/java/woowahan/anifarm/tecolearning/user/controller/UserControllerTest.java
> +                .isOk();
Mono.just 로 안하고 바로 보내는건가요?

2019-12-03 05:38 UTC, yunheehyeon commented on src/frontend/src/components/user/SignUpForm.vue
> +        counter
counter 속성을 사용한 이유는 사용자가 작성한 문자의 길이를 표시하기 위해서 사용했습니다.
counter="10" 을 사용하면 어떤 이점이 있을 까요?

2019-12-03 05:40 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
> +    @Column(nullable = false)
기획의 문제라고 생각하는데 논의가 필요한거 같습니다.

2019-12-03 05:43 UTC, green4469 commented on src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
> +        return ResponseEntity.ok().build();
"/signup" url 네이밍 말씀하시는 건가요?

2019-12-03 05:48 UTC, yunheehyeon commented on src/main/java/woowahan/anifarm/tecolearning/user/service/UserService.java
> +            throw new UserCreateException(error);
언제 로그를 사용할 지 정해보면 어떻까요?

2019-12-03 05:51 UTC, green4469 commented on src/test/java/woowahan/anifarm/tecolearning/user/controller/UserControllerTest.java
> +                .uri("/api/users/signup")
상수처리해서 중복을 제거할 수는 있겠지만, 가독성이 떨어진다고 생각합니다.

예시)
``` java
webTestClient.post()
    .uri("/api/users/signup")

webTestClient.post()
    .uri(USERS_API_URL + "/signup")
```

후자의 경우엔 가독성이 더 떨어지지 않나요?

2019-12-04 01:54 UTC, Deocksoo reviewed
확인 부탁드려요!

2019-12-04 01:54 UTC, Deocksoo commented on src/frontend/src/components/user/SignUpForm.vue
> +      requestSignUp: function () {
아마 requestSignUp() 으로 축약 선언이 가능할거에요, 한번 확인부탁드립니다 :)

2019-12-04 01:54 UTC, Deocksoo commented on src/frontend/src/components/user/UserUpdateForm.vue
> +      />
요 form 부분의 중복을 제거할 수 있을지도 한번 생각해 봐야겠네요!

2019-12-04 01:54 UTC, Deocksoo commented on src/frontend/src/components/user/UserUpdateForm.vue
> +          window.console.log('error:', error); // Print the error if one occurred
주석

2019-12-04 07:43 UTC, ddu0422 approved these changes

2019-12-05 02:11 UTC, Deocksoo approved these changes

2019-12-05 02:11 UTC, Deocksoo commented on src/main/java/woowahan/anifarm/tecolearning/user/domain/AccountStatus.java
> +public enum AccountStatus {
👍  amdin이라던지 차차 여기에 추가하면 관리하기 편하겠네요

2019-12-05 02:12 UTC, ep1stas1s approved these changes

2019-12-05 02:13 UTC, merged